### PR TITLE
Improve uberspace task 

### PR DESCRIPTION
**Pull request by eikes**
I really like your fork of this branch. I was having trouble using it though.

Using the home folder directly to host the code felt better to me.

Nowadays when creating a new uberspace account you get the MySQL users, the first one is a readonly account. By using `scan` on `my_cnf` you get the last match, which is the one you're looking for.

And finally, the command to in the `run` part of the service was not working at all, I corrected it.

### CODE REVIEW

**Comment by mamhoff** [comment]
Wow! Really nice work there. Absolute :+1: for using scan (and actually finding the non-readonly user). 

As for the `:deploy_to` thing: I do agree with your reasoning, but I personally have a couple of projects which are already deployed to `/var/www/virtual/...`. Do you think you could make it configurable, as in: If the `deploy/production.rb` configuration file has a `:deploy_to` set, don't overwrite it? 

Alternatively, you could also split this PR up into two PRs: The `scan` thing is absolutely ready to merge, and the service command, well, works for me, but it looks much better your way. 

Again, thanks for the appreciation and the work!

**Comment by eikes** [comment]
I'll look into this when I'm back from my vacation...

**Comment by eikes** [comment]
Hi!

Better late than never: What do you think of leaving out the line where the deploy_to variable is set entirely and leave it to the user to decide where to deploy to. The default setting in `/var/www/my_app_name` will not work, so a little documentation should included.

see fee723e76f07851deadb6786ec9ee2494f00167a

**Comment by mamhoff** [comment]
Really nice idea! However, what about providing an overridable default so
if you don't really care where its deployed, you don't have to set it?
Thank you for contributing! :cheers:
Am 31.10.2015 12:51 schrieb "Eike Send" notifications@github.com:

**Comment by eikes** [comment]
I tried to implement a default that is set if no other is already set, but if you don't have a :deploy_to target in your `deploy.rb` you will get `"/var/www/#{fetch(:application)}"`

See here:

https://github.com/capistrano/capistrano/blob/44674031a626b3818fd248c788eab3145b60b19d/lib/capistrano/defaults.rb#L13

The only option is detecting if the target is in fact `"/var/www/#{fetch(:application)}"` and then override it again, but that would happen, even if you had explicitly set this in your `deploy.rb`. So that seems like a terrible hack.

**Pull request merged**
